/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package io.jetprocess.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import io.jetprocess.model.FileCorr;
import io.jetprocess.model.FileCorrModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the FileCorr service. Represents a row in the &quot;JET_PROCESS_FileCorr&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>FileCorrModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FileCorrImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FileCorrImpl
 * @generated
 */
@JSON(strict = true)
public class FileCorrModelImpl
	extends BaseModelImpl<FileCorr> implements FileCorrModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a file corr model instance should use the <code>FileCorr</code> interface instead.
	 */
	public static final String TABLE_NAME = "JET_PROCESS_FileCorr";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"fileCorrId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"docFileId", Types.BIGINT},
		{"receiptId", Types.BIGINT}, {"userPostId", Types.BIGINT},
		{"correspondenceType", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fileCorrId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("docFileId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("receiptId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userPostId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("correspondenceType", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table JET_PROCESS_FileCorr (uuid_ VARCHAR(75) null,fileCorrId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,docFileId LONG,receiptId LONG,userPostId LONG,correspondenceType VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table JET_PROCESS_FileCorr";

	public static final String ORDER_BY_JPQL =
		" ORDER BY fileCorr.fileCorrId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY JET_PROCESS_FileCorr.fileCorrId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FILECORRID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public FileCorrModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _fileCorrId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFileCorrId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _fileCorrId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FileCorr.class;
	}

	@Override
	public String getModelClassName() {
		return FileCorr.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<FileCorr, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<FileCorr, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FileCorr, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((FileCorr)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<FileCorr, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<FileCorr, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(FileCorr)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<FileCorr, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<FileCorr, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<FileCorr, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<FileCorr, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<FileCorr, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<FileCorr, Object>>();
		Map<String, BiConsumer<FileCorr, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<FileCorr, ?>>();

		attributeGetterFunctions.put("uuid", FileCorr::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<FileCorr, String>)FileCorr::setUuid);
		attributeGetterFunctions.put("fileCorrId", FileCorr::getFileCorrId);
		attributeSetterBiConsumers.put(
			"fileCorrId", (BiConsumer<FileCorr, Long>)FileCorr::setFileCorrId);
		attributeGetterFunctions.put("groupId", FileCorr::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<FileCorr, Long>)FileCorr::setGroupId);
		attributeGetterFunctions.put("companyId", FileCorr::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<FileCorr, Long>)FileCorr::setCompanyId);
		attributeGetterFunctions.put("userId", FileCorr::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<FileCorr, Long>)FileCorr::setUserId);
		attributeGetterFunctions.put("createDate", FileCorr::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<FileCorr, Date>)FileCorr::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", FileCorr::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<FileCorr, Date>)FileCorr::setModifiedDate);
		attributeGetterFunctions.put("docFileId", FileCorr::getDocFileId);
		attributeSetterBiConsumers.put(
			"docFileId", (BiConsumer<FileCorr, Long>)FileCorr::setDocFileId);
		attributeGetterFunctions.put("receiptId", FileCorr::getReceiptId);
		attributeSetterBiConsumers.put(
			"receiptId", (BiConsumer<FileCorr, Long>)FileCorr::setReceiptId);
		attributeGetterFunctions.put("userPostId", FileCorr::getUserPostId);
		attributeSetterBiConsumers.put(
			"userPostId", (BiConsumer<FileCorr, Long>)FileCorr::setUserPostId);
		attributeGetterFunctions.put(
			"correspondenceType", FileCorr::getCorrespondenceType);
		attributeSetterBiConsumers.put(
			"correspondenceType",
			(BiConsumer<FileCorr, String>)FileCorr::setCorrespondenceType);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getFileCorrId() {
		return _fileCorrId;
	}

	@Override
	public void setFileCorrId(long fileCorrId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fileCorrId = fileCorrId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getDocFileId() {
		return _docFileId;
	}

	@Override
	public void setDocFileId(long docFileId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_docFileId = docFileId;
	}

	@JSON
	@Override
	public long getReceiptId() {
		return _receiptId;
	}

	@Override
	public void setReceiptId(long receiptId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_receiptId = receiptId;
	}

	@JSON
	@Override
	public long getUserPostId() {
		return _userPostId;
	}

	@Override
	public void setUserPostId(long userPostId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userPostId = userPostId;
	}

	@JSON
	@Override
	public String getCorrespondenceType() {
		if (_correspondenceType == null) {
			return "";
		}
		else {
			return _correspondenceType;
		}
	}

	@Override
	public void setCorrespondenceType(String correspondenceType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_correspondenceType = correspondenceType;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(FileCorr.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), FileCorr.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FileCorr toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, FileCorr>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FileCorrImpl fileCorrImpl = new FileCorrImpl();

		fileCorrImpl.setUuid(getUuid());
		fileCorrImpl.setFileCorrId(getFileCorrId());
		fileCorrImpl.setGroupId(getGroupId());
		fileCorrImpl.setCompanyId(getCompanyId());
		fileCorrImpl.setUserId(getUserId());
		fileCorrImpl.setCreateDate(getCreateDate());
		fileCorrImpl.setModifiedDate(getModifiedDate());
		fileCorrImpl.setDocFileId(getDocFileId());
		fileCorrImpl.setReceiptId(getReceiptId());
		fileCorrImpl.setUserPostId(getUserPostId());
		fileCorrImpl.setCorrespondenceType(getCorrespondenceType());

		fileCorrImpl.resetOriginalValues();

		return fileCorrImpl;
	}

	@Override
	public FileCorr cloneWithOriginalValues() {
		FileCorrImpl fileCorrImpl = new FileCorrImpl();

		fileCorrImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		fileCorrImpl.setFileCorrId(
			this.<Long>getColumnOriginalValue("fileCorrId"));
		fileCorrImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		fileCorrImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		fileCorrImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		fileCorrImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		fileCorrImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		fileCorrImpl.setDocFileId(
			this.<Long>getColumnOriginalValue("docFileId"));
		fileCorrImpl.setReceiptId(
			this.<Long>getColumnOriginalValue("receiptId"));
		fileCorrImpl.setUserPostId(
			this.<Long>getColumnOriginalValue("userPostId"));
		fileCorrImpl.setCorrespondenceType(
			this.<String>getColumnOriginalValue("correspondenceType"));

		return fileCorrImpl;
	}

	@Override
	public int compareTo(FileCorr fileCorr) {
		long primaryKey = fileCorr.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof FileCorr)) {
			return false;
		}

		FileCorr fileCorr = (FileCorr)object;

		long primaryKey = fileCorr.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<FileCorr> toCacheModel() {
		FileCorrCacheModel fileCorrCacheModel = new FileCorrCacheModel();

		fileCorrCacheModel.uuid = getUuid();

		String uuid = fileCorrCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			fileCorrCacheModel.uuid = null;
		}

		fileCorrCacheModel.fileCorrId = getFileCorrId();

		fileCorrCacheModel.groupId = getGroupId();

		fileCorrCacheModel.companyId = getCompanyId();

		fileCorrCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			fileCorrCacheModel.createDate = createDate.getTime();
		}
		else {
			fileCorrCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			fileCorrCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			fileCorrCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		fileCorrCacheModel.docFileId = getDocFileId();

		fileCorrCacheModel.receiptId = getReceiptId();

		fileCorrCacheModel.userPostId = getUserPostId();

		fileCorrCacheModel.correspondenceType = getCorrespondenceType();

		String correspondenceType = fileCorrCacheModel.correspondenceType;

		if ((correspondenceType != null) &&
			(correspondenceType.length() == 0)) {

			fileCorrCacheModel.correspondenceType = null;
		}

		return fileCorrCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<FileCorr, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<FileCorr, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FileCorr, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((FileCorr)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<FileCorr, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<FileCorr, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<FileCorr, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((FileCorr)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, FileCorr>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					FileCorr.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _fileCorrId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _docFileId;
	private long _receiptId;
	private long _userPostId;
	private String _correspondenceType;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<FileCorr, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((FileCorr)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("fileCorrId", _fileCorrId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("docFileId", _docFileId);
		_columnOriginalValues.put("receiptId", _receiptId);
		_columnOriginalValues.put("userPostId", _userPostId);
		_columnOriginalValues.put("correspondenceType", _correspondenceType);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("fileCorrId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("docFileId", 128L);

		columnBitmasks.put("receiptId", 256L);

		columnBitmasks.put("userPostId", 512L);

		columnBitmasks.put("correspondenceType", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private FileCorr _escapedModel;

}