info:
    description: "JetProcessRS REST API"
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "JetProcessRS"
    version: v1.0
openapi: 3.0.1
components:
  schemas:
    ReceiptRsModel:
      description: Contains all the data for receipt creation.
      properties:
        id:
          format: int64
          type: integer
        typeId:
          format: int64
          type: integer
        tempfileId:
          format: int64
          type: integer 
        groupId:
          format: int64
          type: integer
        deliveryModeId:
          format: int64
          type: integer
        receiptCategoryId:
          format: int64
          type: integer
        receiptSubCategoryId:
          format: int64
          type: integer
        countryId:
          format: int64
          type: integer
        stateId:
          format: int64
          type: integer
        organizationId:
          format: int64
          type: integer
        subOrganizationId:
          format: int64
          type: integer
        userPostId:
          format: int64
          type: integer
        receivedOn:
          type: string
        letterDate:
          type: string
        referenceNumber:
          type: string
        modeNumber:
          type: string
        subject:
          type: string
        remarks:
          type: string
        name:
          type: string
        designation:
          type: string
        mobile:
          type: string
        email:
          type: string
        address:
          type: string
        pinCode:
          type: string
        city:
          type: string
      type: object
    FileRsModel:
      description: Contains all the data for file creation.
      properties:
        id:
          format: int64
          type: integer
        nature:
          type: string
        type:
          type: string 
        groupId:
          format: int64
          type: integer
        basicHeadId:
          format: int64
          type: integer
        primaryHeadId:
          format: int64
          type: integer
        secondaryHeadId:
          format: int64
          type: integer
        tertiaryHeadId:
          format: int64
          type: integer
        year:
          format: int64
          type: integer
        fileCodeId:
          format: int64
          type: integer
        subject:
          type: string
        fileNumber:
          type: string
      type: object    
paths:
  /createFile:
    post:
      operationId: createFile
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FileRsModel"
          application/xml:
            schema:
              $ref: "#/components/schemas/FileRsModel"
      responses:
        '200':
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/FileRsModel'
            application/xml:
              schema:
                  $ref: '#/components/schemas/FileRsModel'
          description: ''
      tags: ["FileRsModel"]
  /createReceipt:
    post:
      operationId: createReceipt
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReceiptRsModel"
          application/xml:
            schema:
              $ref: "#/components/schemas/ReceiptRsModel"
      responses:
        '200':
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/ReceiptRsModel'
            application/xml:
              schema:
                  $ref: '#/components/schemas/ReceiptRsModel'
          description: ''
      tags: ["ReceiptRsModel"]
      
  