/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package io.jetprocess.masterdata.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the UserPost service. Represents a row in the &quot;Masterdata_UserPost&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>io.jetprocess.masterdata.model.impl.UserPostModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>io.jetprocess.masterdata.model.impl.UserPostImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserPost
 * @generated
 */
@ProviderType
public interface UserPostModel extends BaseModel<UserPost> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user post model instance should use the {@link UserPost} interface instead.
	 */

	/**
	 * Returns the primary key of this user post.
	 *
	 * @return the primary key of this user post
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this user post.
	 *
	 * @param primaryKey the primary key of this user post
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the uuid of this user post.
	 *
	 * @return the uuid of this user post
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this user post.
	 *
	 * @param uuid the uuid of this user post
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the user post ID of this user post.
	 *
	 * @return the user post ID of this user post
	 */
	@AutoEscape
	public String getUserPostId();

	/**
	 * Sets the user post ID of this user post.
	 *
	 * @param userPostId the user post ID of this user post
	 */
	public void setUserPostId(String userPostId);

	/**
	 * Returns the group ID of this user post.
	 *
	 * @return the group ID of this user post
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this user post.
	 *
	 * @param groupId the group ID of this user post
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the post ID of this user post.
	 *
	 * @return the post ID of this user post
	 */
	public long getPostId();

	/**
	 * Sets the post ID of this user post.
	 *
	 * @param postId the post ID of this user post
	 */
	public void setPostId(long postId);

	/**
	 * Returns the section ID of this user post.
	 *
	 * @return the section ID of this user post
	 */
	public long getSectionId();

	/**
	 * Sets the section ID of this user post.
	 *
	 * @param sectionId the section ID of this user post
	 */
	public void setSectionId(long sectionId);

	/**
	 * Returns the description of this user post.
	 *
	 * @return the description of this user post
	 */
	public long getDescription();

	/**
	 * Sets the description of this user post.
	 *
	 * @param description the description of this user post
	 */
	public void setDescription(long description);

	/**
	 * Returns the user name of this user post.
	 *
	 * @return the user name of this user post
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this user post.
	 *
	 * @param userName the user name of this user post
	 */
	public void setUserName(String userName);

	/**
	 * Returns the short name of this user post.
	 *
	 * @return the short name of this user post
	 */
	@AutoEscape
	public String getShortName();

	/**
	 * Sets the short name of this user post.
	 *
	 * @param shortName the short name of this user post
	 */
	public void setShortName(String shortName);

	@Override
	public UserPost cloneWithOriginalValues();

}