/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package io.jetprocess.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ContactDetail service. Represents a row in the &quot;JET_PROCESS_ContactDetail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>io.jetprocess.model.impl.ContactDetailModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>io.jetprocess.model.impl.ContactDetailImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ContactDetail
 * @generated
 */
@ProviderType
public interface ContactDetailModel
	extends BaseModel<ContactDetail>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a contact detail model instance should use the {@link ContactDetail} interface instead.
	 */

	/**
	 * Returns the primary key of this contact detail.
	 *
	 * @return the primary key of this contact detail
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this contact detail.
	 *
	 * @param primaryKey the primary key of this contact detail
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this contact detail.
	 *
	 * @return the uuid of this contact detail
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this contact detail.
	 *
	 * @param uuid the uuid of this contact detail
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the contact detail ID of this contact detail.
	 *
	 * @return the contact detail ID of this contact detail
	 */
	public long getContactDetailId();

	/**
	 * Sets the contact detail ID of this contact detail.
	 *
	 * @param contactDetailId the contact detail ID of this contact detail
	 */
	public void setContactDetailId(long contactDetailId);

	/**
	 * Returns the group ID of this contact detail.
	 *
	 * @return the group ID of this contact detail
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this contact detail.
	 *
	 * @param groupId the group ID of this contact detail
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this contact detail.
	 *
	 * @return the company ID of this contact detail
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this contact detail.
	 *
	 * @param companyId the company ID of this contact detail
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this contact detail.
	 *
	 * @return the user ID of this contact detail
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this contact detail.
	 *
	 * @param userId the user ID of this contact detail
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this contact detail.
	 *
	 * @return the user uuid of this contact detail
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this contact detail.
	 *
	 * @param userUuid the user uuid of this contact detail
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this contact detail.
	 *
	 * @return the user name of this contact detail
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this contact detail.
	 *
	 * @param userName the user name of this contact detail
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this contact detail.
	 *
	 * @return the create date of this contact detail
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this contact detail.
	 *
	 * @param createDate the create date of this contact detail
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this contact detail.
	 *
	 * @return the modified date of this contact detail
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this contact detail.
	 *
	 * @param modifiedDate the modified date of this contact detail
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the min dept oth of this contact detail.
	 *
	 * @return the min dept oth of this contact detail
	 */
	@AutoEscape
	public String getMinDeptOth();

	/**
	 * Sets the min dept oth of this contact detail.
	 *
	 * @param minDeptOth the min dept oth of this contact detail
	 */
	public void setMinDeptOth(String minDeptOth);

	/**
	 * Returns the name of this contact detail.
	 *
	 * @return the name of this contact detail
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this contact detail.
	 *
	 * @param name the name of this contact detail
	 */
	public void setName(String name);

	/**
	 * Returns the designation of this contact detail.
	 *
	 * @return the designation of this contact detail
	 */
	@AutoEscape
	public String getDesignation();

	/**
	 * Sets the designation of this contact detail.
	 *
	 * @param designation the designation of this contact detail
	 */
	public void setDesignation(String designation);

	/**
	 * Returns the mobile of this contact detail.
	 *
	 * @return the mobile of this contact detail
	 */
	@AutoEscape
	public String getMobile();

	/**
	 * Sets the mobile of this contact detail.
	 *
	 * @param mobile the mobile of this contact detail
	 */
	public void setMobile(String mobile);

	/**
	 * Returns the email of this contact detail.
	 *
	 * @return the email of this contact detail
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this contact detail.
	 *
	 * @param email the email of this contact detail
	 */
	public void setEmail(String email);

	/**
	 * Returns the address of this contact detail.
	 *
	 * @return the address of this contact detail
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this contact detail.
	 *
	 * @param address the address of this contact detail
	 */
	public void setAddress(String address);

	/**
	 * Returns the country of this contact detail.
	 *
	 * @return the country of this contact detail
	 */
	@AutoEscape
	public String getCountry();

	/**
	 * Sets the country of this contact detail.
	 *
	 * @param country the country of this contact detail
	 */
	public void setCountry(String country);

	/**
	 * Returns the state of this contact detail.
	 *
	 * @return the state of this contact detail
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this contact detail.
	 *
	 * @param state the state of this contact detail
	 */
	public void setState(String state);

	/**
	 * Returns the district of this contact detail.
	 *
	 * @return the district of this contact detail
	 */
	@AutoEscape
	public String getDistrict();

	/**
	 * Sets the district of this contact detail.
	 *
	 * @param district the district of this contact detail
	 */
	public void setDistrict(String district);

	/**
	 * Returns the pin code of this contact detail.
	 *
	 * @return the pin code of this contact detail
	 */
	@AutoEscape
	public String getPinCode();

	/**
	 * Sets the pin code of this contact detail.
	 *
	 * @param pinCode the pin code of this contact detail
	 */
	public void setPinCode(String pinCode);

	@Override
	public ContactDetail cloneWithOriginalValues();

}