/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package io.jetprocess.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Receipt service. Represents a row in the &quot;JET_PROCESS_Receipt&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>io.jetprocess.model.impl.ReceiptModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>io.jetprocess.model.impl.ReceiptImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Receipt
 * @generated
 */
@ProviderType
public interface ReceiptModel
	extends BaseModel<Receipt>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a receipt model instance should use the {@link Receipt} interface instead.
	 */

	/**
	 * Returns the primary key of this receipt.
	 *
	 * @return the primary key of this receipt
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this receipt.
	 *
	 * @param primaryKey the primary key of this receipt
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this receipt.
	 *
	 * @return the uuid of this receipt
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this receipt.
	 *
	 * @param uuid the uuid of this receipt
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the receipt ID of this receipt.
	 *
	 * @return the receipt ID of this receipt
	 */
	public long getReceiptId();

	/**
	 * Sets the receipt ID of this receipt.
	 *
	 * @param receiptId the receipt ID of this receipt
	 */
	public void setReceiptId(long receiptId);

	/**
	 * Returns the group ID of this receipt.
	 *
	 * @return the group ID of this receipt
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this receipt.
	 *
	 * @param groupId the group ID of this receipt
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this receipt.
	 *
	 * @return the company ID of this receipt
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this receipt.
	 *
	 * @param companyId the company ID of this receipt
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this receipt.
	 *
	 * @return the user ID of this receipt
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this receipt.
	 *
	 * @param userId the user ID of this receipt
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this receipt.
	 *
	 * @return the user uuid of this receipt
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this receipt.
	 *
	 * @param userUuid the user uuid of this receipt
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this receipt.
	 *
	 * @return the user name of this receipt
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this receipt.
	 *
	 * @param userName the user name of this receipt
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this receipt.
	 *
	 * @return the create date of this receipt
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this receipt.
	 *
	 * @param createDate the create date of this receipt
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this receipt.
	 *
	 * @return the modified date of this receipt
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this receipt.
	 *
	 * @param modifiedDate the modified date of this receipt
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the type of this receipt.
	 *
	 * @return the type of this receipt
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this receipt.
	 *
	 * @param type the type of this receipt
	 */
	public void setType(String type);

	/**
	 * Returns the delivery mode of this receipt.
	 *
	 * @return the delivery mode of this receipt
	 */
	@AutoEscape
	public String getDeliveryMode();

	/**
	 * Sets the delivery mode of this receipt.
	 *
	 * @param deliveryMode the delivery mode of this receipt
	 */
	public void setDeliveryMode(String deliveryMode);

	/**
	 * Returns the received on of this receipt.
	 *
	 * @return the received on of this receipt
	 */
	public Date getReceivedOn();

	/**
	 * Sets the received on of this receipt.
	 *
	 * @param receivedOn the received on of this receipt
	 */
	public void setReceivedOn(Date receivedOn);

	/**
	 * Returns the letter date of this receipt.
	 *
	 * @return the letter date of this receipt
	 */
	public Date getLetterDate();

	/**
	 * Sets the letter date of this receipt.
	 *
	 * @param letterDate the letter date of this receipt
	 */
	public void setLetterDate(Date letterDate);

	/**
	 * Returns the reference number of this receipt.
	 *
	 * @return the reference number of this receipt
	 */
	@AutoEscape
	public String getReferenceNumber();

	/**
	 * Sets the reference number of this receipt.
	 *
	 * @param referenceNumber the reference number of this receipt
	 */
	public void setReferenceNumber(String referenceNumber);

	/**
	 * Returns the mode number of this receipt.
	 *
	 * @return the mode number of this receipt
	 */
	@AutoEscape
	public String getModeNumber();

	/**
	 * Sets the mode number of this receipt.
	 *
	 * @param modeNumber the mode number of this receipt
	 */
	public void setModeNumber(String modeNumber);

	/**
	 * Returns the organisation of this receipt.
	 *
	 * @return the organisation of this receipt
	 */
	@AutoEscape
	public String getOrganisation();

	/**
	 * Sets the organisation of this receipt.
	 *
	 * @param organisation the organisation of this receipt
	 */
	public void setOrganisation(String organisation);

	/**
	 * Returns the category of this receipt.
	 *
	 * @return the category of this receipt
	 */
	@AutoEscape
	public String getCategory();

	/**
	 * Sets the category of this receipt.
	 *
	 * @param category the category of this receipt
	 */
	public void setCategory(String category);

	/**
	 * Returns the sub category of this receipt.
	 *
	 * @return the sub category of this receipt
	 */
	@AutoEscape
	public String getSubCategory();

	/**
	 * Sets the sub category of this receipt.
	 *
	 * @param subCategory the sub category of this receipt
	 */
	public void setSubCategory(String subCategory);

	/**
	 * Returns the subject of this receipt.
	 *
	 * @return the subject of this receipt
	 */
	@AutoEscape
	public String getSubject();

	/**
	 * Sets the subject of this receipt.
	 *
	 * @param subject the subject of this receipt
	 */
	public void setSubject(String subject);

	/**
	 * Returns the remarks of this receipt.
	 *
	 * @return the remarks of this receipt
	 */
	@AutoEscape
	public String getRemarks();

	/**
	 * Sets the remarks of this receipt.
	 *
	 * @param remarks the remarks of this receipt
	 */
	public void setRemarks(String remarks);

	/**
	 * Returns the document of this receipt.
	 *
	 * @return the document of this receipt
	 */
	@AutoEscape
	public String getDocument();

	/**
	 * Sets the document of this receipt.
	 *
	 * @param document the document of this receipt
	 */
	public void setDocument(String document);

	/**
	 * Returns the min dept oth of this receipt.
	 *
	 * @return the min dept oth of this receipt
	 */
	@AutoEscape
	public String getMinDeptOth();

	/**
	 * Sets the min dept oth of this receipt.
	 *
	 * @param minDeptOth the min dept oth of this receipt
	 */
	public void setMinDeptOth(String minDeptOth);

	/**
	 * Returns the name of this receipt.
	 *
	 * @return the name of this receipt
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this receipt.
	 *
	 * @param name the name of this receipt
	 */
	public void setName(String name);

	/**
	 * Returns the designation of this receipt.
	 *
	 * @return the designation of this receipt
	 */
	@AutoEscape
	public String getDesignation();

	/**
	 * Sets the designation of this receipt.
	 *
	 * @param designation the designation of this receipt
	 */
	public void setDesignation(String designation);

	/**
	 * Returns the mobile of this receipt.
	 *
	 * @return the mobile of this receipt
	 */
	@AutoEscape
	public String getMobile();

	/**
	 * Sets the mobile of this receipt.
	 *
	 * @param mobile the mobile of this receipt
	 */
	public void setMobile(String mobile);

	/**
	 * Returns the email of this receipt.
	 *
	 * @return the email of this receipt
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this receipt.
	 *
	 * @param email the email of this receipt
	 */
	public void setEmail(String email);

	/**
	 * Returns the address of this receipt.
	 *
	 * @return the address of this receipt
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this receipt.
	 *
	 * @param address the address of this receipt
	 */
	public void setAddress(String address);

	/**
	 * Returns the country of this receipt.
	 *
	 * @return the country of this receipt
	 */
	@AutoEscape
	public String getCountry();

	/**
	 * Sets the country of this receipt.
	 *
	 * @param country the country of this receipt
	 */
	public void setCountry(String country);

	/**
	 * Returns the state of this receipt.
	 *
	 * @return the state of this receipt
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this receipt.
	 *
	 * @param state the state of this receipt
	 */
	public void setState(String state);

	/**
	 * Returns the district of this receipt.
	 *
	 * @return the district of this receipt
	 */
	@AutoEscape
	public String getDistrict();

	/**
	 * Sets the district of this receipt.
	 *
	 * @param district the district of this receipt
	 */
	public void setDistrict(String district);

	/**
	 * Returns the pin code of this receipt.
	 *
	 * @return the pin code of this receipt
	 */
	@AutoEscape
	public String getPinCode();

	/**
	 * Sets the pin code of this receipt.
	 *
	 * @param pinCode the pin code of this receipt
	 */
	public void setPinCode(String pinCode);

	/**
	 * Returns the receipt number of this receipt.
	 *
	 * @return the receipt number of this receipt
	 */
	@AutoEscape
	public String getReceiptNumber();

	/**
	 * Sets the receipt number of this receipt.
	 *
	 * @param receiptNumber the receipt number of this receipt
	 */
	public void setReceiptNumber(String receiptNumber);

	@Override
	public Receipt cloneWithOriginalValues();

}