create table JET_PROCESS_ContactDetail (
	uuid_ VARCHAR(75) null,
	contactDetailId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	minDeptOth VARCHAR(75) null,
	name VARCHAR(75) null,
	designation VARCHAR(75) null,
	mobile VARCHAR(75) null,
	email VARCHAR(75) null,
	address VARCHAR(75) null,
	country VARCHAR(75) null,
	state_ VARCHAR(75) null,
	district VARCHAR(75) null,
	pinCode VARCHAR(75) null
);

create table JET_PROCESS_DocFile (
	uuid_ VARCHAR(75) null,
	docFileId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	nature VARCHAR(75) null,
	type_ VARCHAR(75) null,
	subject VARCHAR(75) null,
	fileNumber VARCHAR(75) null,
	category VARCHAR(75) null,
	subCategory VARCHAR(75) null,
	remarks VARCHAR(75) null,
	reference VARCHAR(75) null
);

create table JET_PROCESS_Receipt (
	uuid_ VARCHAR(75) null,
	receiptId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	createdOn DATE null,
	type_ VARCHAR(75) null,
	deliveryMode VARCHAR(75) null,
	receivedOn DATE null,
	letterDate DATE null,
	referenceNumber VARCHAR(75) null,
	modeNumber VARCHAR(75) null,
	organisation VARCHAR(75) null,
	category VARCHAR(75) null,
	subCategory VARCHAR(75) null,
	subject VARCHAR(75) null,
	remarks VARCHAR(75) null,
	document VARCHAR(75) null,
	senderId LONG
);